[project]
name = "classifier"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.133.0",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
]
